### ISSUE TITLE
HTTP+HTTPS server simultaneously

### ISSUE THREAD

**Issue by helllamer** [ChicagoBoss/ChicagoBoss#191]
It will be good to listen HTTP and HTTPS ports simultaneously. Current easy-to-use variant, `CB` + `nginx` as proxy, crashes on chunked encoding and other `HTTP/1.1` features. This is because nginx does not support `HTTP/1.1`.

By now, other possible crunches are:
* `CB` + `apache` + `mod_proxy` + `mod_ssl` - it works! But have much more complexity (compared with `nginx`).
* Run two instances of `CB` in cluster: disadvantages are overhead of session replication, double RAM consumption and overall system design looks ugly.

Also, a patch was proposed some time ago.
Hope, this will be implemented in future.

[Original message from google-groups](https://groups.google.com/d/topic/chicagoboss/ap5YSCEbySE/discussion).
Some related patches was in pull-request #44 "Multiple listeners".

**Comment by danikp** [comment]
At time of writing this comment, NGINX working fine with CB for all protocols it supports including SPDY. Also, there is ways to distinguish http and https traffic. And for all webservers' related stuff we rely on simple_bridge, so that feature should be implemented there, may be as part of nitrogen/simple_bridge#35
