### ISSUE TITLE
Aleppo compile failed

### ISSUE THREAD

**Issue by pixelfields** [ChicagoBoss/ChicagoBoss#522]
Hi all, 
I try to compile CB, but it's failed on aleppo. Errors are following:

`==> aleppo (compile)
/usr/lib/erlang/lib/parsetools-2.0.11/include/yeccpre.hrl: no such file or directory
src/aleppo_parser.yrl: Warning: conflicts: 1 shift/reduce, 0 reduce/reduce
Compiling /data2/src/erlangapps/ChicagoBoss/deps/aleppo/src/aleppo_parser.yrl failed:
/usr/lib/erlang/lib/parsetools-2.0.11/include/yeccpre.hrl:none: no such file or directory
/data2/src/erlangapps/ChicagoBoss/deps/aleppo/src/aleppo_parser.yrl:none: Warning: conflicts: 1 shift/reduce, 0 reduce/reduce
ERROR: compile failed while processing /data2/src/erlangapps/ChicagoBoss/deps/aleppo: rebar_abort
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1`

OS: Debian Testing
Erlang version: Erlang/OTP 17 [erts-6.2] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
CB version: v0.8.10, v0.8.12, v0.8.13

Could anybody help me with this issue?

Thanks a lot.

Dusan Simek

**Comment by danikp** [comment]
nice to know everything solved.
closing

**Comment by quentusrex** [comment]
It's not solved. The build system doesn't check for dependencies properly, and the docs don't refer to which packages to install for a pain free installation.

**Comment by danikp** [comment]
I cannot help with libraries on your system, but new version of CB will be released very soon with all dependencies updated.

**Comment by noizu** [comment]
This really isn't a chicago boss bug. The bug is on Rebar and Aleppo not properly stating missing dependencies. 

running off of latest esl-erlang on ubuntu works for me on this however. 

wget http://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
yes "" | dpkg -i erlang-solutions_1.0_all.deb
yes "" | apt-get update
yes "" | apt-get install elixir
yes "" | apt-get install esl-erlang
yes "" | apt-get install erlang-xmerl
