### ISSUE TITLE
Running boss_migrate:make fails if there's no priv/migrations directory

### ISSUE THREAD

**Issue by batasrki** [ChicagoBoss/ChicagoBoss#543]
Hey guys,

I was playing around with CB and wanted to make a migration. The above happens if that directory isn't present. The error is fairly opaque, just ```{error,enoent}```.

Is there a possibility to detect and create the directory **or** make the error more programmer-friendly?

**Comment by davidw** [comment]
That sounds reasonable. +1

**Comment by batasrki** [comment]
If someone points me in the right direction, I can attempt to make this change.

**Comment by kshamko** [comment]
I believe that required module for the changes is boss_migrate. It's source can be found here PATH_TO_YOUR_APP/deps/boss/src/boss/boss_migrate.erl. make/2 function should be changed (line 16).  However I was not able to reproduce this issue after default installation of CB. The issue was reproduced when I manually deleted priv/migrations folder.

**Comment by batasrki** [comment]
It might be fixed in the latest version. I'll try again.

**Comment by danikp** [comment]
/priv/migrations created by default on new projects. not an issue anymore
