### ISSUE TITLE
Question: Parameterized modules are no longer supported 

### ISSUE THREAD

**Issue by diorahman** [ChicagoBoss/ChicagoBoss#622]
Hi!

First of all thanks for the great effort for this opensource project! Super cool!

I'm new to Erlang and got this: "parameterized modules are no longer supported" message in my editor, at this line:

```erlang
-module(hello_boss_greeting_controller, [Req]).
```
Surprisingly, the app seems work fine (ran `./init-dev.sh` and got the expected response).

Anyone could help me explaining this? Thank you!

**Comment by choptastic** [comment]
Hi,

CB uses Parameterized modules through the use of a parse transform that
makes them possible.

CB's make process inserts the parse transform dynamically during
compilation so that you don't have to add the parse transform explicitly.
But that can make editors wonk our if they do "vanilla" compilation for
highlighting errors.

-Jesse

--
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm

**Comment by diorahman** [comment]
OK Thanks, will ignore that particular error (for a while?). Any tips for vim users?

**Comment by danikp** [comment]
do you have some syntax check plugin installed?
